VermilionCity_Text_GrimerMultipliesInSludge::
    .string "We're careful about pollution here.\p"
    .string "We've heard GRIMER multiplies in\n"
    .string "toxic sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in VERMILION about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My POKéMON is tamping the land\n"
    .string "to lay the foundation.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "A MACHOP is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign::
    .string "VERMILION CITY\n"
    .string "The Port of Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN CLUB\n"
    .string "All POKéMON fans welcome!$"

VermilionCity_Text_GymSign::
    .string "VERMILION CITY POKéMON GYM\n"
    .string "LEADER: LT. SURGE\l"
    .string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from PROF. OAK\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"

VermilionCity_Text_SquirtleTrainer::
    .string "I just caught a SQUIRTLE that was\n"
    .string "always getting into mischief.\p"
    .string "I think it needs a good trainer to\n"
    .string "set it straight.$"

VermilionCity_Text_BadgeGet::
    .string "You have the THUNDER BADGE?!\n"
    .string "You must be a good trainer!\p"
    .string "I just caught a SQUIRTLE that was\n"
    .string "always getting into mischief.\p"
    .string "Would you take good care of it?$"

VermilionCity_Text_HowsSquirtle::
    .string "How is SQUIRTLE doing?$"

VermilionCity_Text_ObtainedSquirtleFromMelanie::
    .string "{PLAYER} received a SQUIRTLE\n"
    .string "from JENNY!$"

VermilionCity_Text_SquirtleGet::
    .string "Okay! Please treat SQUIRTLE right!$"

VermilionCity_Text_SquirtleDeclined::
    .string "Oh… what am I to do now?$"

VermilionCity_Text_CutMan::
    .string "Have you seen these trees around?\p"
    .string "My boys and I are trying to get\n"
    .string "rid of them but these guys are\p"
    .string "tough and it seems like they're\n"
    .string "everywhere.$"

VermilionCity_Text_ShouldICut::
    .string "Hey, you've got the HM for CUT!\p"
    .string "Do you mind if I borrow this? I\n"
    .string "think this is just the thing that\p"
    .string "we need to get rid of the trees.$"

VermilionCity_Text_OhWell::
    .string "Figured I should ask in case.\n"
    .string "Don't worry, we'll get 'em\p"
    .string "all at some point.$"

VermilionCity_Text_HandedHM01::
    .string "{PLAYER} lent HM01 to a\n"
    .string "strange man?$"

VermilionCity_Text_ComeBack::
    .string "We should be done in a bit,\n"
    .string "go take a walk and come back.$"

VermilionCity_Text_WeCutTheTrees::
    .string "Whew… That was a lot of hard\n"
    .string "work. We really couldn't\p"
    .string "have done it without your\n"
    .string "kindness!$"
