CeruleanCity_House3_Text_PleaseTradeWithMyHusband:: @ 8191F80
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"

CeruleanCity_House3_Text_BulbasaurTrainer::
    .string "Hi! My name's MELANIE.\p"
    .string "I've been taking care of injured\n"
    .string "POKéMON with the help of my\p"
    .string "BULBASAUR, but now that we've\n"
    .string "treated everyone, I think\p"
    .string "BULBASAUR needs a better home\n"
    .string "with a strong trainer.$"

CeruleanCity_House3_Text_BadgeGet::
    .string "Oh, that's the BOULDER BADGE!\p"
    .string "Would you please take BULBASAUR\n"
    .string "with you?$"

CeruleanCity_House3_Text_HowsBulbasaur::
    .string "How's it going? I think you'll\n"
    .string "find BULBASAUR to be very\p"
    .string "helpful in MISTY's GYM!$"

CeruleanCity_House3_Text_ObtainedBulbasaurFromMelanie::
    .string "{PLAYER} received a BULBASAUR\n"
    .string "from MELANIE!$"

CeruleanCity_House3_Text_BulbasaurDeclined::
    .string "Oh… Okay. I'm sure a trainer\n"
    .string "like yourself could make do.$"

