CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"

CeruleanCity_House3_Text_BulbasaurTrainer::
    .string "Hi! My name's MELANIE.\p"
    .string "I've been taking care of injured\n"
    .string "POKéMON with the help of this\p"
    .string "BULBASAUR, but now that we've\n"
    .string "treated everyone, I think\p"
    .string "BULBASAUR needs a better home\n"
    .string "with a good trainer.$"

CeruleanCity_House3_Text_HighFriendship::
    .string "Your POKéMON seem very happy\n"
    .string "with you!\p"
    .string "Would you take care of this\n"
    .string "BULBASAUR?$"

CeruleanCity_House3_Text_HowsBulbasaur::
    .string "How is everything?\p"
    .string "I think BULBASAUR will be\n"
    .string "very helpful in MISTY's GYM!$"

CeruleanCity_House3_Text_ObtainedBulbasaurFromMelanie::
    .string "{PLAYER} received a BULBASAUR\n"
    .string "from MELANIE!$"

CeruleanCity_House3_Text_BulbasaurDeclined::
    .string "Oh… Okay. I'm sure a trainer\n"
    .string "like yourself could make do.$"

